# Generated by Django 4.1.7 on 2026-03-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('running', 'Running'), ('walking', 'Walking'), ('cycling', 'Cycling'), ('strength', 'Strength Training'), ('yoga', 'Yoga'), ('swimming', 'Swimming'), ('basketball', 'Basketball'), ('other', 'Other')], max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers', max_digits=6, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-date_logged'],
            },
        ),
    ]
