# Generated by Django 4.1.7 on 2026-03-24 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='team_participants',
            field=models.ManyToManyField(blank=True, related_name='challenges', to='teams.team'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='won_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='winning_teams',
            field=models.ManyToManyField(blank=True, related_name='won_challenges', to='teams.team'),
        ),
    ]
