# Generated by Django 4.1.7 on 2026-03-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_workout', 'First Workout'), ('streak_7_days', '7-Day Streak'), ('streak_14_days', '14-Day Streak'), ('streak_30_days', '30-Day Streak'), ('points_100', '100 Points Earned'), ('points_500', '500 Points Earned'), ('points_1000', '1000 Points Earned'), ('team_join', 'First Team Join'), ('team_victory', 'Team Victory'), ('distance_10k', '10K Distance'), ('distance_50k', '50K Distance'), ('activities_50', '50 Activities'), ('activities_100', '100 Activities')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('badge_image', models.URLField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'achievements',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_streaks',
            },
        ),
    ]
